site_name: COOLERCHIPS
repo_url: https://github.com/NREL/COOLERCHIPS-Technical-Evaluation-Team
repo_name: NREL/COOLERCHIPS
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
      - navigation.indexes
markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Home: 
    - index.md
  # - Example Section: 
  #   - example_section/index.md
  #   - Example Page: example_section/page.md
